language: php
 
php:
    - 5.3

addons:
  hosts:
    - nodeprint.com
    - nodeprint.dev

before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - WEBROOT="$(pwd)"
    - CGIROOT=`dirname "$(which php-cgi)"`
    - echo "WEBROOT: $WEBROOT"
    - echo "CGIROOT: $CGIROOT"
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - sudo echo "<VirtualHost *:80>
        DocumentRoot $WEBROOT
        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory $WEBROOT >
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

      		# Configure PHP as CGI
      		ScriptAlias /local-bin $CGIROOT
      		DirectoryIndex index.php index.html
      		AddType application/x-httpd-php5 .php
      		Action application/x-httpd-php5 '/local-bin/php-cgi'
      
      </VirtualHost>" | sudo tee /etc/apache2/sites-available/default > /dev/null

    - cat /etc/apache2/sites-available/default
    - mysql -e 'CREATE DATABASE `vx`;'
    - pwd
    - sudo service apache2 restart
script: 
    - php ./application/test/test.php
