language: php
 
php:
    - 5.4

addons:
  hosts:
    - nodeprint.com
    - nodeprint.dev

before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - WEBROOT="$(pwd)"
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "$(curl -fsSL https://gist.github.com/airyland/2b66dba908e004ff4754/raw/74f4fec92c064c4f683fef28a6098caf0f038de7/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
    - echo "$(curl -fsSL https://gist.github.com/airyland/93d2c15fcf5551181e9b/raw/8066fda124b6c86f69ad32a010b8c22bbaf868e8/gistfile1.txt)" | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - cat /etc/apache2/sites-available/default
    - mysql -e 'CREATE DATABASE `vx`;'
    - mysql -e use vx
    - mysql -e source /home/travis/build/airyland/nodeprint/application/db/np_data.sql
    - mysql -e show tables
    - pwd
    - sudo service apache2 restart
script: 
    - php ./application/test/test.php
    - sudo cat /var/log/apache2/access.log
    - sudo cat /var/log/apache2/error.log
